name: windows build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4.1.5

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        # DOTNET_VERSION: Update to the correct .NET version.
        dotnet-version: 9.0.x

    - name: Build everything
      run: |
        & .\eng\build.ps1 -build $true

    - name: Run unit tests
      run: |
        & .\eng\build.ps1 -build $false -test $true

    - name: Test artifact publishing
      run: |
        & .\eng\build.ps1 -build $false -publish $true
