name: windows build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.101' # SDK Version to use; x will use the latest version of the 6.0 channel. Force 101 for global.json compatibility.

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
          vs-prerelease: true

    - name: Build everything
      run: |
        & .\eng\build.ps1 -build $true

    - name: Run unit tests
      run: |
        & .\eng\build.ps1 -build $false -test $true

    - name: Test artifact publishing
      run: |
        & .\eng\build.ps1 -build $false -publish $true
